# Generated by Django 3.0.8 on 2020-09-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=13, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marker',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
