# Generated by Django 2.2.7 on 2021-02-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_group_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='account/images/x.png', null=True, upload_to='account/images/'),
        ),
    ]
