# Generated by Django 2.2.7 on 2021-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200822_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
