# Generated by Django 2.2.7 on 2021-01-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210131_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_task', to='todo.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_task', to='todo.Task'),
        ),
    ]
