# Generated by Django 2.2.7 on 2021-02-28 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0006_auto_20210226_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_reminder_task', to='todo.Task')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_reminder_to', to=settings.AUTH_USER_MODEL)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_reminder_who', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
