# Generated by Django 2.2.7 on 2021-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_sharereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ShareReminder',
        ),
    ]
