# Generated by Django 3.0.8 on 2020-12-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.CharField(max_length=10)),
                ('mode', models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('DOC', 'Document')], default='IMG', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='thumb',
            field=models.ImageField(blank=True, default='album/images/folder_240.png', null=True, upload_to='album/images/'),
        ),
    ]
