# Generated by Django 3.0.8 on 2020-12-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20201213_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='youtube',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extention',
            name='mode',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('DOC', 'Document'), ('UKN', 'Unknown'), ('LNK', 'Link'), ('YTB', 'YouTube')], default='IMG', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='mode',
            field=models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('DOC', 'Document'), ('UKN', 'Unknown'), ('LNK', 'Link'), ('YTB', 'YouTube')], default='IMG', max_length=3),
        ),
    ]
