# Generated by Django 3.0.8 on 2020-12-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20201214_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='album/images/'),
        ),
    ]
