# Generated by Django 3.0.8 on 2020-12-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_album_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
