# Generated by Django 3.0.8 on 2020-12-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20201220_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='max_image_height',
            field=models.IntegerField(blank=True, default=786, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='max_image_width',
            field=models.IntegerField(blank=True, default=1366, null=True),
        ),
    ]
