# Generated by Django 3.0.8 on 2020-12-25 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_auto_20201225_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='album.Animation'),
        ),
    ]
