# Generated by Django 3.0.8 on 2020-12-26 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0009_album_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='animation',
            name='keyframes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='animation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animations', to=settings.AUTH_USER_MODEL),
        ),
    ]
