# Generated by Django 3.0.8 on 2020-12-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_animation_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='text',
        ),
    ]
