# Generated by Django 3.0.8 on 2020-12-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_remove_animation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='watermark',
            field=models.ImageField(blank=True, null=True, upload_to='album/images/'),
        ),
        migrations.AddField(
            model_name='animation',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
