# Generated by Django 3.0.8 on 2020-12-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0013_auto_20201228_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='interval',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='album',
            name='opacity',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='album',
            name='watermark',
            field=models.ImageField(blank=True, null=True, upload_to='album/watermarks/'),
        ),
    ]
