# Generated by Django 3.0.8 on 2021-01-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0014_auto_20201228_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='count',
            field=models.CharField(default='infinite', max_length=20),
        ),
        migrations.AddField(
            model_name='animation',
            name='delay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='animation',
            name='direction',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='animation',
            name='fill',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='animation',
            name='timing',
            field=models.CharField(default='ease', max_length=20),
        ),
        migrations.AlterField(
            model_name='animation',
            name='keyframes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
