# Generated by Django 2.2.7 on 2021-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0016_animation_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='session_key',
            field=models.CharField(blank=True, default='none', max_length=50, null=True),
        ),
    ]
