# Generated by Django 2.2.7 on 2021-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
