# Generated by Django 3.0.8 on 2020-09-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20200916_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
