# Generated by Django 3.0.8 on 2020-09-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20200916_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
