# Generated by Django 2.2.7 on 2021-02-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20210223_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='folders.Folder'),
        ),
    ]
